name: Tmate session
on:
  push:
    paths:
      - .github/workflows/tmate-session.yaml

jobs:
  tmate-session:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
