name: Vulnerability-scan
on:
  push:
    paths:
      - .github/workflows/vulnerability-scan.yaml

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2      

      - name: Fetch image
        run: |
          docker pull vulnerables/web-dvwa:latest
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/vulnerables/web-dvwa:latest'
          format: 'table'
          #exit-code: '1'
          #ignore-unfixed: true
          #severity: 'CRITICAL,HIGH'
